"""SQLAlchemy persistence models.

Importing this package registers every model on ``Base.metadata`` so that
``create_all`` and Alembic autogenerate see the complete schema.
"""

from rosalind.adapters.outbound.persistence.models.account import (
    Account,
    AccountIdentity,
)
from rosalind.adapters.outbound.persistence.models.base import Base, utcnow
from rosalind.adapters.outbound.persistence.models.email import (
    EmailAttachment,
    EmailMessage,
    EmailMessageObservation,
    EmailParticipant,
    EmailTag,
    EmailThread,
)
from rosalind.adapters.outbound.persistence.models.imports import Import, ImportFile
from rosalind.adapters.outbound.persistence.models.person import (
    Person,
    PersonAddress,
    PersonAddressAssertion,
    PersonDate,
    PersonDateAssertion,
    PersonEmail,
    PersonEmailAssertion,
    PersonGender,
    PersonGenderAssertion,
    PersonIm,
    PersonImAssertion,
    PersonLocale,
    PersonLocaleAssertion,
    PersonName,
    PersonNameAssertion,
    PersonNickname,
    PersonNicknameAssertion,
    PersonNote,
    PersonNoteAssertion,
    PersonOrganization,
    PersonOrganizationAssertion,
    PersonPhone,
    PersonPhoneAssertion,
    PersonRelation,
    PersonRelationAssertion,
    PersonUrl,
    PersonUrlAssertion,
    SourceAssertion,
    SourceIdentity,
)
from rosalind.adapters.outbound.persistence.models.source import (
    OAuthAuthRequest,
    OAuthCredential,
    SourceAccount,
    SourceRecord,
)

__all__ = [
    "Account",
    "AccountIdentity",
    "Base",
    "EmailAttachment",
    "EmailMessage",
    "EmailMessageObservation",
    "EmailParticipant",
    "EmailTag",
    "EmailThread",
    "Import",
    "ImportFile",
    "OAuthAuthRequest",
    "OAuthCredential",
    "Person",
    "PersonAddress",
    "PersonAddressAssertion",
    "PersonDate",
    "PersonDateAssertion",
    "PersonEmail",
    "PersonEmailAssertion",
    "PersonGender",
    "PersonGenderAssertion",
    "PersonIm",
    "PersonImAssertion",
    "PersonLocale",
    "PersonLocaleAssertion",
    "PersonName",
    "PersonNameAssertion",
    "PersonNickname",
    "PersonNicknameAssertion",
    "PersonNote",
    "PersonNoteAssertion",
    "PersonOrganization",
    "PersonOrganizationAssertion",
    "PersonPhone",
    "PersonPhoneAssertion",
    "PersonRelation",
    "PersonRelationAssertion",
    "PersonUrl",
    "PersonUrlAssertion",
    "SourceAccount",
    "SourceAssertion",
    "SourceIdentity",
    "SourceRecord",
    "utcnow",
]
