"""Online search domain: the request DTO, the search enums, and the plan.

Phase 0 owns the request side; Phase 1 adds the ``SearchPlan`` / ``ShortCircuit``
produced by Prepare, per ``docs/features/search_plan_schema.py``.
"""

from rosalind.application.search.fusion import FusedCandidate, FusedCandidates, fuse
from rosalind.application.search.plan import (
    MAX_LIMIT,
    Budgets,
    Cursor,
    FusionConfig,
    FusionStrategy,
    IndexVersions,
    InvalidSearchRequest,
    LexicalQuery,
    ListPosition,
    PlanHints,
    PlanWarning,
    PreparedQuery,
    PrepareResult,
    PrepareTimings,
    Presentation,
    QueryVector,
    RequestContext,
    ResolvedEntity,
    ResolvedFilters,
    Scope,
    SearchPlan,
    SearchStrategy,
    ShortCircuit,
    ShortCircuitReason,
    WarningCode,
    vector_digest,
)
from rosalind.application.search.request import (
    Direction,
    GroupBy,
    ResultView,
    SearchMode,
    SearchRequest,
    SearchRequestFilters,
    SortOrder,
)
from rosalind.application.search.rerank import (
    ChunkText,
    RerankBackendError,
    RerankedHit,
    RerankError,
    RerankInput,
    RerankResult,
    RerankStats,
    RerankTextMode,
    rerank,
)
from rosalind.application.search.retrieve import FilterPath, LexicalHit, LexicalResult
from rosalind.application.search.semantic import (
    SemanticFilterPath,
    SemanticHit,
    SemanticResult,
    SemanticRetrievalError,
)

__all__ = [
    "MAX_LIMIT",
    "Budgets",
    "ChunkText",
    "Cursor",
    "Direction",
    "FilterPath",
    "FusedCandidate",
    "FusedCandidates",
    "FusionConfig",
    "FusionStrategy",
    "GroupBy",
    "IndexVersions",
    "InvalidSearchRequest",
    "LexicalHit",
    "LexicalQuery",
    "LexicalResult",
    "ListPosition",
    "PlanHints",
    "PlanWarning",
    "PrepareResult",
    "PrepareTimings",
    "PreparedQuery",
    "Presentation",
    "QueryVector",
    "RequestContext",
    "RerankBackendError",
    "RerankError",
    "RerankInput",
    "RerankResult",
    "RerankStats",
    "RerankTextMode",
    "RerankedHit",
    "ResolvedEntity",
    "ResolvedFilters",
    "ResultView",
    "Scope",
    "SearchMode",
    "SearchPlan",
    "SearchRequest",
    "SearchRequestFilters",
    "SearchStrategy",
    "SemanticFilterPath",
    "SemanticHit",
    "SemanticResult",
    "SemanticRetrievalError",
    "ShortCircuit",
    "ShortCircuitReason",
    "SortOrder",
    "WarningCode",
    "fuse",
    "rerank",
    "vector_digest",
]
